[package]
name         = "meta-signal-aggregator"
version      = "0.4.0"
edition      = "2024"
rust-version = "1.89"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/LiGoldragon/meta-signal-aggregator"
description  = "Meta Signal configuration contract for aggregator."
publish      = false

[lib]
name = "meta_signal_aggregator"
path = "src/lib.rs"

[features]
default = ["dotos-text"]
dotos-text = ["signal-frame/dotos-text", "signal-aggregator/dotos-text"]

[dependencies]
dotos              = { package = "dotos", git = "https://github.com/LiGoldragon/dotos.git", rev = "80c7b17f7ad3cf547d2624c6a243e5de5f85c9f3" }
signal-frame      = { git = "https://github.com/LiGoldragon/signal-frame.git", rev = "8aa0bcaeb29fe9e461a11706a469638d2fd109ac" }
signal-aggregator = { git = "https://github.com/LiGoldragon/signal-aggregator", rev = "5d2b80e21f1a79b1025731d269ceb03c64f26d5b" }
rkyv              = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
thiserror         = "2"

[lints.rust]
unsafe_code = "forbid"
unused      = { level = "warn", priority = -1 }
dead_code   = "warn"
